### ISSUE TITLE
Create plan for tracking Data Display and Data Retrieval time to update the site

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2968]
- [x] Number of issues closed related to bugs vs. maintenance/data updates vs. enhancements
- [x] Does DR have a way of identifying how much time they spend compiling data for us?
- [ ] Number of updates that are made on schedule--timeline from when data is available to when data makes it on website
- [ ] Ability for more than one member of the NRRD team to make data updates (with ONRR furnished equipment)
Number of manual steps vs. automated steps in update process
- [x] How much manually curated content vs. data driven content there is on the site

**Comment by jennmalcolm** [comment]
@NBrannberg, welcome to our repo! We are happy to have you.

Can you provide us any info on Shannon's second check box in this issue? Would it be possible to determine how much time you all are spending on our requests? If not yet, is it possible to implement something? 

We are in the midst of implement some metrics and measurements that will help us determine how successful we are at managing NRRD, and we consider the level of effort coming from Data Retrieval to be a relevant factor (along with many others).

**Comment by NBrannberg** [comment]
Yes, we track all of our hours.  We will compile all of the hours for the portal data that has been provided in the last three years.

**Comment by mcharg** [comment]
@usEITI Wants us to start tracking this sooner rather than later, as we're doing things that save us time.

**Comment by jennmalcolm** [comment]
For the first check box, we have reports available through mural that we can use. The one issue I see that will make this more difficult is that we are consistently applying our epic labels, but we should probably use either one of the bug labels or the enhancement labels as well in most cases to make this analysis easier. I will keep this in mind with future sprint planning. I can also go through all of the issues since January to classify into these two categories so that we have our baseline data. I'll create a share Google doc to track these issues. The addition of the sizes will also help as a proxy to measure the time dedicated to each type of issue, but we only added that a couple months ago, so we won't have that for all of the baseline data. 

I will also create a google spreadsheet to track our timeline for data updates. Nathan and I will be discussing our potential schedule for next CY in a couple weeks.

**Comment by brentryanjohnson** [comment]
Great idea, @jennmalcolm. I'll add a column to the audit worksheet for manually curated data.

**Comment by jennmalcolm** [comment]
@lpgoldstein is helping me with this plan. We're documenting it here: https://docs.google.com/spreadsheets/d/1W7rmcFFrXCvWL_9ty6iqDfNkxpRBOwnP3xV70mrC6IU/edit#gid=0 (limited access).
